language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8
  - TOX_ENV=pep8
  - TOX_ENV=coverage
install:
  - pip install tox
script:
  - tox -e $TOX_ENV

branches:
  only:
    - master
    - develop
    - /^release.*$/
